"use client"

import type { SimulationResult, SimulationInputs } from "@/lib/simulation-engine"
import { formatCurrency, formatNumber, formatPercent } from "@/lib/simulation-engine"

export async function generatePDF(inputs: SimulationInputs, result: SimulationResult) {
  // Dynamic import for client-side only
  const { jsPDF } = await import("jspdf")

  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  let y = 20

  // Helper functions
  const addTitle = (text: string, size = 20) => {
    doc.setFontSize(size)
    doc.setTextColor(139, 92, 246) // Purple
    doc.text(text, margin, y)
    y += size / 2 + 5
  }

  const addSubtitle = (text: string) => {
    doc.setFontSize(14)
    doc.setTextColor(100, 100, 100)
    doc.text(text, margin, y)
    y += 10
  }

  const addText = (text: string, x: number = margin) => {
    doc.setFontSize(11)
    doc.setTextColor(60, 60, 60)
    doc.text(text, x, y)
    y += 7
  }

  const addMetric = (label: string, value: string) => {
    doc.setFontSize(10)
    doc.setTextColor(100, 100, 100)
    doc.text(label, margin, y)
    doc.setFontSize(12)
    doc.setTextColor(30, 30, 30)
    doc.text(value, margin + 80, y)
    y += 8
  }

  const addLine = () => {
    doc.setDrawColor(200, 200, 200)
    doc.line(margin, y, pageWidth - margin, y)
    y += 10
  }

  // Header
  addTitle("FORMATDISC MVP Simulator", 24)
  addSubtitle("Business Model Validation Report")
  y += 5
  addLine()

  // Verdict Section
  const verdictColors = {
    GO: [34, 197, 94],
    MAYBE: [245, 158, 11],
    NO_GO: [239, 68, 68],
  }
  const verdictLabels = {
    GO: "GO - Ready to Launch",
    MAYBE: "MAYBE - Needs Optimization",
    NO_GO: "NO GO - Pivot Required",
  }

  doc.setFillColor(...(verdictColors[result.verdict] as [number, number, number]))
  doc.roundedRect(margin, y, pageWidth - margin * 2, 25, 3, 3, "F")

  doc.setFontSize(16)
  doc.setTextColor(255, 255, 255)
  doc.text(verdictLabels[result.verdict], pageWidth / 2, y + 15, { align: "center" })
  y += 35

  doc.setFontSize(10)
  doc.setTextColor(80, 80, 80)
  const splitReason = doc.splitTextToSize(result.verdictReason, pageWidth - margin * 2)
  doc.text(splitReason, margin, y)
  y += splitReason.length * 5 + 10
  addLine()

  // Credit Rating
  addTitle("Institutional Credit Rating", 16)
  doc.setFontSize(28)
  doc.setTextColor(30, 30, 30)
  doc.text(result.confidence.rating, pageWidth / 2, y + 15, { align: "center" })
  y += 30
  addLine()

  // Input Parameters
  addTitle("Input Parameters", 14)
  y += 5
  addMetric("Monthly Leads", formatNumber(inputs.monthlyLeads))
  addMetric("Conversion Rate", formatPercent(inputs.conversionRate))
  addMetric("Monthly Price", formatCurrency(inputs.price))
  addMetric("Customer Acquisition Cost", formatCurrency(inputs.cac))
  addMetric("Monthly Churn Rate", formatPercent(inputs.churnRate))
  addMetric("Validation Score", `${inputs.validationScore}/100`)
  addMetric("Projection Horizon", `${inputs.horizonMonths} months`)
  y += 5
  addLine()

  // Key Metrics
  addTitle("Key Metrics", 14)
  y += 5
  addMetric("Final Customers", formatNumber(result.summary.finalCustomers))
  addMetric("Final MRR", formatCurrency(result.summary.finalMRR))
  addMetric("Total Revenue", formatCurrency(result.summary.totalRevenue))
  addMetric("Total Profit", formatCurrency(result.summary.totalProfit))
  addMetric("Customer LTV", formatCurrency(result.summary.ltv))
  addMetric("LTV/CAC Ratio", `${result.summary.ltvCacRatio.toFixed(2)}x`)
  addMetric("Payback Period", `${result.summary.paybackPeriod.toFixed(1)} months`)
  addMetric(
    "Break-even Month",
    result.summary.breakEvenMonth ? `Month ${result.summary.breakEvenMonth}` : "Not achieved",
  )
  y += 5
  addLine()

  // Confidence Score
  addTitle("Confidence Analysis", 14)
  y += 5
  addMetric("Overall Confidence", `${Math.round(result.confidence.score)}/100`)
  y += 5

  result.confidence.factors.forEach((factor) => {
    const impactEmoji = factor.impact === "positive" ? "✓" : factor.impact === "neutral" ? "○" : "✗"
    addMetric(
      `${impactEmoji} ${factor.name}`,
      `${Math.round(factor.score)} (${Math.round(factor.weight * 100)}% weight)`,
    )
  })

  // Footer
  y = doc.internal.pageSize.getHeight() - 20
  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  doc.text("Generated by FORMATDISC MVP Simulator | www.formatdisc.hr", pageWidth / 2, y, { align: "center" })
  doc.text(`Report Date: ${new Date().toLocaleDateString()}`, pageWidth / 2, y + 5, { align: "center" })

  // Save
  doc.save(`FORMATDISC-MVP-Report-${new Date().toISOString().split("T")[0]}.pdf`)
}
